FROM centos:6.7
MAINTAINER Boudewijn Rempt <boud@valdyas.org>
ADD https://github.com/boudewijnrempt/AppImages/raw/master/recipes/krita/Recipe /Recipe
#RUN bash -ex Recipe && yum clean all && rm -rf /out && rm -rf krita*
